// <auto-generated />
using System;
using Calorie_Calculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calorie_Calculator.Migrations
{
    [DbContext(typeof(Steps_dContext))]
    partial class Steps_dContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calorie_Calculator.Models.Steps_d", b =>
                {
                    b.Property<DateTime>("Hist")
                        .HasColumnType("datetime2");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.HasKey("Hist");

                    b.ToTable("Steps_Ds");
                });
#pragma warning restore 612, 618
        }
    }
}
